In [41]:
import pandas as pd
import numpy as np

# Thiết lập hiển thị cho console
pd.set_option('display.max_rows', 10)
pd.set_option('display.max_columns', None)

print("--- BẮT ĐẦU HƯỚNG DẪN PANDAS TRUNG CẤP ---\n")

--- BẮT ĐẦU HƯỚNG DẪN PANDAS TRUNG CẤP ---

In [42]:

# ==============================================================================
# 1. TẠO DATAFRAME MẪU
# ==============================================================================
print("1. TẠO DATAFRAME MẪU")
data = {
    'Mã_SP': ['A001', 'A002', 'B003', 'A004', 'B005', 'C006', 'A007', 'C008'],
    'Danh_Mục': ['Điện tử', 'Quần áo', 'Điện tử', 'Đồ gia dụng', 'Điện tử', 'Quần áo', 'Đồ gia dụng', 'Quần áo'],
    'Giá': [1200, 350, np.nan, 800, 2500, 450, 150, 900],
    'Số_Lượng_Bán': [100, 250, 80, 120, 40, 300, 200, 50],
    'Khu_Vực': ['Miền Bắc', 'Miền Nam', 'Miền Bắc', 'Miền Trung', 'Miền Nam', 'Miền Bắc', 'Miền Nam', 'Miền Trung']
}
df = pd.DataFrame(data)
print("DataFrame Ban Đầu:")
print(df)
print("-" * 50)

1. TẠO DATAFRAME MẪU
DataFrame Ban Đầu:
  Mã_SP     Danh_Mục     Giá  Số_Lượng_Bán     Khu_Vực
0  A001      Điện tử  1200.0           100    Miền Bắc
1  A002      Quần áo   350.0           250    Miền Nam
2  B003      Điện tử     NaN            80    Miền Bắc
3  A004  Đồ gia dụng   800.0           120  Miền Trung
4  B005      Điện tử  2500.0            40    Miền Nam
5  C006      Quần áo   450.0           300    Miền Bắc
6  A007  Đồ gia dụng   150.0           200    Miền Nam
7  C008      Quần áo   900.0            50  Miền Trung
--------------------------------------------------

In [43]:

# ==============================================================================
# 2. LẬP CHỈ MỤC VÀ TRUY VẤN NÂNG CAO (.loc, .iloc, Boolean Indexing)
# ==============================================================================
print("2. LẬP CHỈ MỤC VÀ TRUY VẤN NÂNG CAO")

# 2.1. Lập chỉ mục bằng nhãn (.loc)
# Chọn các hàng từ chỉ mục 1 đến 5 (bao gồm cả 5) và chỉ lấy cột 'Danh_Mục' và 'Giá'
df_loc = df.loc[1:5, ['Danh_Mục', 'Giá']]
print("\n2.1. Chọn Hàng (1-5) và Cột ('Danh_Mục', 'Giá') bằng .loc:")
print(df_loc)

# 2.2. Lập chỉ mục bằng vị trí (.iloc)
# Chọn các hàng từ vị trí 0 đến 4 (không bao gồm 5) và cột thứ 1 và 3
df_iloc = df.iloc[0:5, [1, 3]]
print("\n2.2. Chọn Hàng (0-4) và Cột (vị trí 1, 3) bằng .iloc:")
print(df_iloc)

# 2.3. Lập chỉ mục Boolean (Truy vấn theo điều kiện)
# Chọn các sản phẩm thuộc danh mục 'Điện tử' VÀ có 'Giá' > 1000
df_filter = df[(df['Danh_Mục'] == 'Điện tử') & (df['Giá'] > 1000)]
print("\n2.3. Lọc: Sản phẩm Điện tử có Giá > 1000:")
print(df_filter)
print("-" * 50)

2. LẬP CHỈ MỤC VÀ TRUY VẤN NÂNG CAO

2.1. Chọn Hàng (1-5) và Cột ('Danh_Mục', 'Giá') bằng .loc:
      Danh_Mục     Giá
1      Quần áo   350.0
2      Điện tử     NaN
3  Đồ gia dụng   800.0
4      Điện tử  2500.0
5      Quần áo   450.0

2.2. Chọn Hàng (0-4) và Cột (vị trí 1, 3) bằng .iloc:
      Danh_Mục  Số_Lượng_Bán
0      Điện tử           100
1      Quần áo           250
2      Điện tử            80
3  Đồ gia dụng           120
4      Điện tử            40

2.3. Lọc: Sản phẩm Điện tử có Giá > 1000:
  Mã_SP Danh_Mục     Giá  Số_Lượng_Bán   Khu_Vực
0  A001  Điện tử  1200.0           100  Miền Bắc
4  B005  Điện tử  2500.0            40  Miền Nam
--------------------------------------------------

In [44]:

# ==============================================================================
# 3. XỬ LÝ DỮ LIỆU THIẾU (MISSING DATA - NaN)
# ==============================================================================
print("3. XỬ LÝ DỮ LIỆU THIẾU")

# 3.1. Kiểm tra dữ liệu thiếu
print("\n3.1. Kiểm tra dữ liệu thiếu (True=Thiếu):")
print(df.isnull().sum())

# 3.2. Xóa các hàng chứa NaN (dropna)
# Tạo bản sao để không thay đổi df gốc
df_dropna = df.copy().dropna(subset=['Giá'])
print("\n3.2. DataFrame sau khi xóa hàng có NaN trong cột 'Giá':")
print(df_dropna)

# 3.3. Điền giá trị thiếu (fillna)
# Thay thế các giá trị thiếu trong cột 'Giá' bằng giá trị trung bình (mean) của cột đó
mean_price = df['Giá'].mean()
df_fillna = df.copy()
df_fillna['Giá'] = df_fillna['Giá'].fillna(mean_price)
print("\n3.3. DataFrame sau khi điền giá trị thiếu bằng Giá trung bình (%.2f):" % mean_price)
print(df_fillna)
print("-" * 50)

3. XỬ LÝ DỮ LIỆU THIẾU

3.1. Kiểm tra dữ liệu thiếu (True=Thiếu):
Mã_SP           0
Danh_Mục        0
Giá             1
Số_Lượng_Bán    0
Khu_Vực         0
dtype: int64

3.2. DataFrame sau khi xóa hàng có NaN trong cột 'Giá':
  Mã_SP     Danh_Mục     Giá  Số_Lượng_Bán     Khu_Vực
0  A001      Điện tử  1200.0           100    Miền Bắc
1  A002      Quần áo   350.0           250    Miền Nam
3  A004  Đồ gia dụng   800.0           120  Miền Trung
4  B005      Điện tử  2500.0            40    Miền Nam
5  C006      Quần áo   450.0           300    Miền Bắc
6  A007  Đồ gia dụng   150.0           200    Miền Nam
7  C008      Quần áo   900.0            50  Miền Trung

3.3. DataFrame sau khi điền giá trị thiếu bằng Giá trung bình (907.14):
  Mã_SP     Danh_Mục          Giá  Số_Lượng_Bán     Khu_Vực
0  A001      Điện tử  1200.000000           100    Miền Bắc
1  A002      Quần áo   350.000000           250    Miền Nam
2  B003      Điện tử   907.142857            80    Miền Bắc
3  A004  Đồ gia dụng   800.000000           120  Miền Trung
4  B005      Điện tử  2500.000000            40    Miền Nam
5  C006      Quần áo   450.000000           300    Miền Bắc
6  A007  Đồ gia dụng   150.000000           200    Miền Nam
7  C008      Quần áo   900.000000            50  Miền Trung
--------------------------------------------------

In [45]:

# ==============================================================================
# 4. GOM NHÓM VÀ TÍNH TOÁN TỔNG HỢP (GROUPBY)
# ==============================================================================
print("4. GOM NHÓM VÀ TÍNH TOÁN TỔNG HỢP (GROUPBY)")

# 4.1. Tính tổng Số Lượng Bán theo Danh Mục
# Tính tổng số lượng bán và giá trung bình cho mỗi Danh Mục
df_group_category = df.groupby('Danh_Mục').agg(
    Tong_SL_Ban=('Số_Lượng_Bán', 'sum'),
    Gia_TB=('Giá', 'mean'),
    So_Luong_SP=('Mã_SP', 'count')
).reset_index() # reset_index để đưa 'Danh_Mục' từ index thành cột

print("\n4.1. Tổng hợp theo Danh Mục:")
print(df_group_category)

# 4.2. Groupby theo nhiều cột
df_group_multi = df.groupby(['Khu_Vực', 'Danh_Mục'])['Số_Lượng_Bán'].sum().reset_index()
print("\n4.2. Tổng hợp Số Lượng Bán theo Khu Vực và Danh Mục:")
print(df_group_multi)
print("-" * 50)

4. GOM NHÓM VÀ TÍNH TOÁN TỔNG HỢP (GROUPBY)

4.1. Tổng hợp theo Danh Mục:
      Danh_Mục  Tong_SL_Ban       Gia_TB  So_Luong_SP
0      Quần áo          600   566.666667            3
1      Điện tử          220  1850.000000            3
2  Đồ gia dụng          320   475.000000            2

4.2. Tổng hợp Số Lượng Bán theo Khu Vực và Danh Mục:
      Khu_Vực     Danh_Mục  Số_Lượng_Bán
0    Miền Bắc      Quần áo           300
1    Miền Bắc      Điện tử           180
2    Miền Nam      Quần áo           250
3    Miền Nam      Điện tử            40
4    Miền Nam  Đồ gia dụng           200
5  Miền Trung      Quần áo            50
6  Miền Trung  Đồ gia dụng           120
--------------------------------------------------

In [46]:

# ==============================================================================
# 5. KẾT HỢP (MERGING) DATAFRAME
# ==============================================================================
print("5. KẾT HỢP (MERGING) DATAFRAME")

# Tạo DataFrame phụ chứa thông tin khuyến mãi
promotion_data = {
    'Danh_Mục': ['Điện tử', 'Quần áo', 'Đồ gia dụng', 'Văn phòng'],
    'Khuyến_Mãi': ['Giảm 15%', 'Tặng kèm', 'Giảm 5%', 'Giảm 10%']
}
df_promo = pd.DataFrame(promotion_data)
print("\nDataFrame Khuyến Mãi:")
print(df_promo)

# Kết hợp df_fillna (đã xử lý NaN) với df_promo
# Loại kết hợp 'left': giữ tất cả các hàng từ df_fillna
df_merged = pd.merge(
    df_fillna,
    df_promo,
    on='Danh_Mục',
    how='left'
)
print("\nDataFrame sau khi Merge (Left Join) với Khuyến Mãi:")
print(df_merged)
print("-" * 50)

5. KẾT HỢP (MERGING) DATAFRAME

DataFrame Khuyến Mãi:
      Danh_Mục Khuyến_Mãi
0      Điện tử   Giảm 15%
1      Quần áo   Tặng kèm
2  Đồ gia dụng    Giảm 5%
3    Văn phòng   Giảm 10%

DataFrame sau khi Merge (Left Join) với Khuyến Mãi:
  Mã_SP     Danh_Mục          Giá  Số_Lượng_Bán     Khu_Vực Khuyến_Mãi
0  A001      Điện tử  1200.000000           100    Miền Bắc   Giảm 15%
1  A002      Quần áo   350.000000           250    Miền Nam   Tặng kèm
2  B003      Điện tử   907.142857            80    Miền Bắc   Giảm 15%
3  A004  Đồ gia dụng   800.000000           120  Miền Trung    Giảm 5%
4  B005      Điện tử  2500.000000            40    Miền Nam   Giảm 15%
5  C006      Quần áo   450.000000           300    Miền Bắc   Tặng kèm
6  A007  Đồ gia dụng   150.000000           200    Miền Nam    Giảm 5%
7  C008      Quần áo   900.000000            50  Miền Trung   Tặng kèm
--------------------------------------------------

In [47]:

# ==============================================================================
# 6. BIẾN ĐỔI DỮ LIỆU VỚI .apply() và .map()
# ==============================================================================
print("6. BIẾN ĐỔI DỮ LIỆU VỚI .apply() VÀ .map()")

# 6.1. Sử dụng .apply() với Lambda/Hàm (Áp dụng cho cột)
# Tính cột Doanh Thu Ước Tính = Giá * Số Lượng Bán
df_merged['Doanh_Thu_Uoc_Tinh'] = df_merged.apply(
    lambda row: row['Giá'] * row['Số_Lượng_Bán'],
    axis=1 # axis=1 để áp dụng hàm trên mỗi hàng
)

print("\n6.1. Thêm cột Doanh_Thu_Uoc_Tinh (Giá * Số_Lượng_Bán):")
print(df_merged[['Mã_SP', 'Giá', 'Số_Lượng_Bán', 'Doanh_Thu_Uoc_Tinh']].head())

# 6.2. Sử dụng .map() (Áp dụng cho Series/Cột đơn)
# Chuẩn hóa cột Khuyến_Mãi thành giá trị số (15, 0, 5, 10)
def extract_discount(promo_str):
    if '15%' in promo_str: return 15
    if '5%' in promo_str: return 5
    if '10%' in promo_str: return 10
    return 0 # Tặng kèm hoặc NaN sẽ là 0

df_merged['Phan_Tram_KM'] = df_merged['Khuyến_Mãi'].map(extract_discount)

print("\n6.2. Thêm cột Phan_Tram_KM bằng .map() và hàm tùy chỉnh:")
print(df_merged[['Khuyến_Mãi', 'Phan_Tram_KM']].head())
print("-" * 50)

6. BIẾN ĐỔI DỮ LIỆU VỚI .apply() VÀ .map()

6.1. Thêm cột Doanh_Thu_Uoc_Tinh (Giá * Số_Lượng_Bán):
  Mã_SP          Giá  Số_Lượng_Bán  Doanh_Thu_Uoc_Tinh
0  A001  1200.000000           100       120000.000000
1  A002   350.000000           250        87500.000000
2  B003   907.142857            80        72571.428571
3  A004   800.000000           120        96000.000000
4  B005  2500.000000            40       100000.000000

6.2. Thêm cột Phan_Tram_KM bằng .map() và hàm tùy chỉnh:
  Khuyến_Mãi  Phan_Tram_KM
0   Giảm 15%            15
1   Tặng kèm             0
2   Giảm 15%            15
3    Giảm 5%             5
4   Giảm 15%            15
--------------------------------------------------

In [48]:

# ==============================================================================
# 7. PHÂN TÍCH CHUỖI THỜI GIAN (TIME SERIES)
# ==============================================================================
print("7. PHÂN TÍCH CHUỖI THỜI GIAN (TIME SERIES)")

# 7.1. Tạo DataFrame Chuỗi Thời Gian Mẫu
dates = pd.date_range(start='2024-01-01', periods=12, freq='M') # 12 tháng, kết thúc mỗi tháng
sales_data = {
    'Ngày': dates,
    'Doanh_Thu': [10000, 11500, 10800, 13000, 14500, 12000, 15000, 16200, 17000, 15500, 18000, 20000]
}
df_ts = pd.DataFrame(sales_data)

# Chuyển cột 'Ngày' thành index (DatetimeIndex)
df_ts = df_ts.set_index('Ngày')

print("\n7.1. DataFrame Chuỗi Thời Gian (Index là Ngày):")
print(df_ts)

# 7.2. Lập chỉ mục theo thời gian
# Chọn tất cả dữ liệu trong quý đầu tiên (Q1)
print("\n7.2. Lọc dữ liệu Quý 1 (2024-01 đến 2024-03):")
print(df_ts.loc['2024-01':'2024-03'])

# 7.3. Tính toán với cửa sổ trượt (Rolling Window)
# Tính giá trị trung bình trượt (rolling mean) trong 3 tháng
df_ts['Doanh_Thu_TB_3_Thang'] = df_ts['Doanh_Thu'].rolling(window=3).mean()

print("\n7.3. Tính Doanh Thu Trung Bình Trượt 3 Tháng (Rolling Mean):")
print(df_ts)

# 7.4. Lấy mẫu lại (Resampling)
# Giả sử đây là dữ liệu hàng ngày, ta muốn tổng hợp theo Quý (Quarterly)
# Tạo một chuỗi thời gian hàng ngày để minh họa Resampling
daily_dates = pd.date_range(start='2024-01-01', periods=30, freq='D')
np.random.seed(42)
daily_sales = pd.Series(np.random.randint(500, 2000, size=30), index=daily_dates)

# Resample: Tổng hợp dữ liệu hàng ngày thành tổng Doanh Thu theo tuần (W)
weekly_sales = daily_sales.resample('W').sum()

print("\n7.4. Resample: Tổng hợp Doanh Thu Hàng Ngày thành Tổng Hàng Tuần (W):")
print(weekly_sales)
print("-" * 50)

7. PHÂN TÍCH CHUỖI THỜI GIAN (TIME SERIES)

7.1. DataFrame Chuỗi Thời Gian (Index là Ngày):
            Doanh_Thu
Ngày
2024-01-31      10000
2024-02-29      11500
2024-03-31      10800
2024-04-30      13000
2024-05-31      14500
...               ...
2024-08-31      16200
2024-09-30      17000
2024-10-31      15500
2024-11-30      18000
2024-12-31      20000

[12 rows x 1 columns]

7.2. Lọc dữ liệu Quý 1 (2024-01 đến 2024-03):
            Doanh_Thu
Ngày
2024-01-31      10000
2024-02-29      11500
2024-03-31      10800

7.3. Tính Doanh Thu Trung Bình Trượt 3 Tháng (Rolling Mean):
            Doanh_Thu  Doanh_Thu_TB_3_Thang
Ngày
2024-01-31      10000                   NaN
2024-02-29      11500                   NaN
2024-03-31      10800          10766.666667
2024-04-30      13000          11766.666667
2024-05-31      14500          12766.666667
...               ...                   ...
2024-08-31      16200          14400.000000
2024-09-30      17000          16066.666667
2024-10-31      15500          16233.333333
2024-11-30      18000          16833.333333
2024-12-31      20000          17833.333333

[12 rows x 2 columns]

7.4. Resample: Tổng hợp Doanh Thu Hàng Ngày thành Tổng Hàng Tuần (W):
2024-01-07    11508
2024-01-14     8620
2024-01-21     9505
2024-01-28     8779
2024-02-04     2358
Freq: W-SUN, dtype: int64
--------------------------------------------------

/var/folders/c0/k8s4b0396w9f0x0rw25n4ybw0000gp/T/ipykernel_14488/1179955241.py:7: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  dates = pd.date_range(start='2024-01-01', periods=12, freq='M') # 12 tháng, kết thúc mỗi tháng